# SwiftLint Configuration for MacCleaner

# Paths to exclude from linting
excluded:
  - .build
  - .swiftpm
  - MacCleaner.app
  - docs

# Enabled rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments
  - line_length # Will configure separately

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 80

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - url
    - URL

type_name:
  min_length: 3
  max_length: 50

# Force unwrapping
force_unwrapping: warning

# Force cast
force_cast: warning

# Force try
force_try: warning

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Custom rules
custom_rules:
  double_space:
    regex: "([a-z,A-Z] \\ {2,}[a-z,A-Z])"
    message: "Double space between words"
    severity: warning
